# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ihor-pyvovarnyk/Documents/Workspace/oae-sound-processing-tool/resources/gui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(572, 357)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 551, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.selected_file = QtGui.QLineEdit(self.groupBox)
        self.selected_file.setGeometry(QtCore.QRect(10, 30, 531, 21))
        self.selected_file.setReadOnly(True)
        self.selected_file.setObjectName(_fromUtf8("selected_file"))
        self.select_file_btn = QtGui.QPushButton(self.groupBox)
        self.select_file_btn.setGeometry(QtCore.QRect(430, 50, 113, 32))
        self.select_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_file_btn.setAcceptDrops(False)
        self.select_file_btn.setObjectName(_fromUtf8("select_file_btn"))
        self.invalid_file_label = QtGui.QLabel(self.groupBox)
        self.invalid_file_label.setGeometry(QtCore.QRect(10, 60, 411, 16))
        self.invalid_file_label.setObjectName(_fromUtf8("invalid_file_label"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 130, 551, 161))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 114))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.info_labels_container = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.info_labels_container.setMargin(11)
        self.info_labels_container.setSpacing(6)
        self.info_labels_container.setObjectName(_fromUtf8("info_labels_container"))
        self.info_file_name_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.info_file_name_label.setObjectName(_fromUtf8("info_file_name_label"))
        self.info_labels_container.addWidget(self.info_file_name_label)
        self.info_sampling_frequency_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.info_sampling_frequency_label.setObjectName(_fromUtf8("info_sampling_frequency_label"))
        self.info_labels_container.addWidget(self.info_sampling_frequency_label)
        self.info_bitrate_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.info_bitrate_label.setObjectName(_fromUtf8("info_bitrate_label"))
        self.info_labels_container.addWidget(self.info_bitrate_label)
        self.info_duration_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.info_duration_label.setObjectName(_fromUtf8("info_duration_label"))
        self.info_labels_container.addWidget(self.info_duration_label)
        self.info_channels_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.info_channels_label.setObjectName(_fromUtf8("info_channels_label"))
        self.info_labels_container.addWidget(self.info_channels_label)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 10, 371, 114))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.info_values_container = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.info_values_container.setMargin(11)
        self.info_values_container.setSpacing(6)
        self.info_values_container.setObjectName(_fromUtf8("info_values_container"))
        self.info_file_name_value = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.info_file_name_value.setObjectName(_fromUtf8("info_file_name_value"))
        self.info_values_container.addWidget(self.info_file_name_value)
        self.info_sampling_frequency_value = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.info_sampling_frequency_value.setObjectName(_fromUtf8("info_sampling_frequency_value"))
        self.info_values_container.addWidget(self.info_sampling_frequency_value)
        self.info_bitrate_value = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.info_bitrate_value.setObjectName(_fromUtf8("info_bitrate_value"))
        self.info_values_container.addWidget(self.info_bitrate_value)
        self.info_duration_value = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.info_duration_value.setObjectName(_fromUtf8("info_duration_value"))
        self.info_values_container.addWidget(self.info_duration_value)
        self.info_channels_value = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.info_channels_value.setObjectName(_fromUtf8("info_channels_value"))
        self.info_values_container.addWidget(self.info_channels_value)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.select_extension_label = QtGui.QLabel(self.tab_2)
        self.select_extension_label.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.select_extension_label.setObjectName(_fromUtf8("select_extension_label"))
        self.convert_target_ext_combo_box = QtGui.QComboBox(self.tab_2)
        self.convert_target_ext_combo_box.setGeometry(QtCore.QRect(170, 10, 104, 26))
        self.convert_target_ext_combo_box.setObjectName(_fromUtf8("convert_target_ext_combo_box"))
        self.convert_btn = QtGui.QPushButton(self.tab_2)
        self.convert_btn.setGeometry(QtCore.QRect(290, 10, 113, 32))
        self.convert_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convert_btn.setObjectName(_fromUtf8("convert_btn"))
        self.convert_status_label = QtGui.QLabel(self.tab_2)
        self.convert_status_label.setGeometry(QtCore.QRect(420, 10, 111, 31))
        self.convert_status_label.setObjectName(_fromUtf8("convert_status_label"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.cut_audio_duration_label = QtGui.QLabel(self.tab_3)
        self.cut_audio_duration_label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.cut_audio_duration_label.setObjectName(_fromUtf8("cut_audio_duration_label"))
        self.cut_audio_duration_value = QtGui.QLabel(self.tab_3)
        self.cut_audio_duration_value.setGeometry(QtCore.QRect(120, 10, 411, 16))
        self.cut_audio_duration_value.setObjectName(_fromUtf8("cut_audio_duration_value"))
        self.cut_start_from_label = QtGui.QLabel(self.tab_3)
        self.cut_start_from_label.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.cut_start_from_label.setObjectName(_fromUtf8("cut_start_from_label"))
        self.cut_start_from_edit = QtGui.QLineEdit(self.tab_3)
        self.cut_start_from_edit.setGeometry(QtCore.QRect(90, 40, 113, 21))
        self.cut_start_from_edit.setObjectName(_fromUtf8("cut_start_from_edit"))
        self.cut_length_label = QtGui.QLabel(self.tab_3)
        self.cut_length_label.setGeometry(QtCore.QRect(250, 40, 61, 21))
        self.cut_length_label.setObjectName(_fromUtf8("cut_length_label"))
        self.cut_length_edit = QtGui.QLineEdit(self.tab_3)
        self.cut_length_edit.setGeometry(QtCore.QRect(310, 40, 113, 21))
        self.cut_length_edit.setObjectName(_fromUtf8("cut_length_edit"))
        self.cut_btn = QtGui.QPushButton(self.tab_3)
        self.cut_btn.setGeometry(QtCore.QRect(10, 70, 113, 32))
        self.cut_btn.setObjectName(_fromUtf8("cut_btn"))
        self.cut_status_label = QtGui.QLabel(self.tab_3)
        self.cut_status_label.setGeometry(QtCore.QRect(150, 70, 111, 31))
        self.cut_status_label.setObjectName(_fromUtf8("cut_status_label"))
        self.cut_invalid_values_label = QtGui.QLabel(self.tab_3)
        self.cut_invalid_values_label.setGeometry(QtCore.QRect(450, 40, 91, 21))
        self.cut_invalid_values_label.setObjectName(_fromUtf8("cut_invalid_values_label"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.stop_btn = QtGui.QPushButton(self.centralWidget)
        self.stop_btn.setGeometry(QtCore.QRect(500, 100, 61, 32))
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.play_btn = QtGui.QPushButton(self.centralWidget)
        self.play_btn.setGeometry(QtCore.QRect(390, 100, 61, 32))
        self.play_btn.setObjectName(_fromUtf8("play_btn"))
        self.player_slider = QtGui.QSlider(self.centralWidget)
        self.player_slider.setGeometry(QtCore.QRect(9, 100, 381, 22))
        self.player_slider.setOrientation(QtCore.Qt.Horizontal)
        self.player_slider.setObjectName(_fromUtf8("player_slider"))
        self.pause_btn = QtGui.QPushButton(self.centralWidget)
        self.pause_btn.setGeometry(QtCore.QRect(440, 100, 61, 32))
        self.pause_btn.setObjectName(_fromUtf8("pause_btn"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 572, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Select file", None))
        self.select_file_btn.setText(_translate("MainWindow", "Select File", None))
        self.invalid_file_label.setText(_translate("MainWindow", "Wrong file format", None))
        self.info_file_name_label.setText(_translate("MainWindow", "File Name:", None))
        self.info_sampling_frequency_label.setText(_translate("MainWindow", "Sampling Frequency:", None))
        self.info_bitrate_label.setText(_translate("MainWindow", "Bitrate:", None))
        self.info_duration_label.setText(_translate("MainWindow", "Duration:", None))
        self.info_channels_label.setText(_translate("MainWindow", "Channels:", None))
        self.info_file_name_value.setText(_translate("MainWindow", "file_name", None))
        self.info_sampling_frequency_value.setText(_translate("MainWindow", "sampling_frequency", None))
        self.info_bitrate_value.setText(_translate("MainWindow", "bitrate", None))
        self.info_duration_value.setText(_translate("MainWindow", "duration", None))
        self.info_channels_value.setText(_translate("MainWindow", "channels", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Information", None))
        self.select_extension_label.setText(_translate("MainWindow", "Select target extension", None))
        self.convert_btn.setText(_translate("MainWindow", "Convert", None))
        self.convert_status_label.setText(_translate("MainWindow", "convert_status_label", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Convert", None))
        self.cut_audio_duration_label.setText(_translate("MainWindow", "Audio duration:", None))
        self.cut_audio_duration_value.setText(_translate("MainWindow", "cut_audio_duration", None))
        self.cut_start_from_label.setText(_translate("MainWindow", "Start from", None))
        self.cut_length_label.setText(_translate("MainWindow", "Length", None))
        self.cut_btn.setText(_translate("MainWindow", "Cut", None))
        self.cut_status_label.setText(_translate("MainWindow", "cut_status_label", None))
        self.cut_invalid_values_label.setText(_translate("MainWindow", "Invalid values", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Cut", None))
        self.stop_btn.setText(_translate("MainWindow", "Stop", None))
        self.play_btn.setText(_translate("MainWindow", "Play", None))
        self.pause_btn.setText(_translate("MainWindow", "Pause", None))

